#pipelines:
#  path: kubeflow/pipeline
#  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJleHAiOjQ4NjgxNzk4MTMsImlhdCI6MTYyODE3OTgxMywiaXNzIjoiREt1YmUifQ.WbdyrdywEEMk7OD6KEyU8C_HVmXStE_gXgKNQfNnGxVmrrCqBHBV9ZNPYg_g7mk8XTbA3mZ2iJ86sFr9DmXk2yNx-8-Na9zL3XkVPf-a6nE-33QGf1PBemg9s-l-PJ7pWrEXOWttUKRJTJ2M9ZEpUAi9AZZ5UfOvVpudga0bh_XbLmvP7TPCnVOk0g0kvBDWIVvaEvEpznO2WcWYFXUVEh80Okx5205lvGuv9ajQLkphbiNdnnGOV6Wr8TG3WIvN1M5e-74Hj13fUZU7Db1SiQfD2qqidrF5VdLqEK2nDP2y60XaynbWf1XiTqtj70-b8u_zUCU9q3yylDbR1TUigg
#  pipelines:
#    - name: workflow-dkube.py
#      run: true

Dockerfile: Dockerfile
